// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    heartbeatIntervalMs: 10000, // 10 seconds
    timeoutMs: 30000, // 30 seconds
    reconnect: true,
    reconnectMaxAttempts: 3,
    reconnectIntervalMs: 5000 // 5 seconds
  }
});

// Secure subscription wrapper
interface SubscriptionOptions {
  table: string;
  filter?: string;
  callback: (payload: any) => void;
}

export const secureSubscribe = async (options: SubscriptionOptions) => {
  const { table, filter, callback } = options;

  // Validate table name against allowed list
  const allowedTables = ['memory_game_sessions', 'rewards_transactions'];
  if (!allowedTables.includes(table)) {
    throw new Error(`Subscription to table ${table} is not allowed`);
  }

  // Create subscription
  const subscription = supabase
    .channel('custom-all-channel')
    .on(
      'postgres_changes',
      { 
        event: '*',
        schema: 'public',
        table: table,
        filter: filter
      },
      callback
    )
    .subscribe();

  // Return cleanup function
  return () => {
    subscription.unsubscribe();
  };
};

export const validateSessionState = (state: any) => {
  const requiredFields = ['game_id', 'host_id', 'player_ids', 'game_state', 'current_player_id'];
  const missingFields = requiredFields.filter(field => !(field in state));
  if (missingFields.length > 0) {
    throw new Error(`Invalid session state: Missing fields ${missingFields.join(', ')}`);
  }

  if (!Array.isArray(state.player_ids)) {
    throw new Error('Invalid session state: player_ids must be an array');
  }

  if (typeof state.game_state !== 'object') {
    throw new Error('Invalid session state: game_state must be an object');
  }

  return true;
};